### ISSUE TITLE
Should react to comment surrounded by punctation

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/ircbot#1]
e.g.

```
(01:41:39) CeBe: yii\base\Object, 123
(01:41:48) CeBe: yii\base\Object
(01:41:48) Gillette: yii\base\Object is the base class that implements the *property* feature. http://www.yiiframework.com/doc-2.0/yii-base-object.html
```

first one should also work.

**Comment by tom--** [comment]
I wonder if the best place to trim punctuation is immediately before [this line](https://github.com/yiisoft-contrib/ircbot/blob/master/bot.js#L326).

Trimming period . and comma , from the end of the `word` would cover most of the cases I think we've seen.

**Comment by cebe** [comment]
looks like a good place on first sight. I have not understood the whole code structure yet, though.

**Comment by tom--** [comment]
Do you want to understand it? Because if no, I can add this fairly easily. But if yes, am I responsible for making it hard to understand, e.g. with inadequate comments or obscure code?

**Comment by cebe** [comment]
I wanted to but I have no time for it and also will not have in the next few weeks. You can go ahead and add it.

**Comment by tom--** [comment]
Try out the fix in #yii and close if ok.

**Comment by cebe** [comment]
does not seem to have an effect:

```
(23:26:41) CeBe: yii\base\Object
(23:26:42) Gillette: yii\base\Object is the base class that implements the *property* feature. http://www.yiiframework.com/doc-2.0/yii-base-object.html
(23:26:44) CeBe: yii\base\Object,
(23:26:54) CeBe: yii\base\Object, 123
(23:27:16) CeBe: tom[]: is the punctuation fix already deployed?
```

**Comment by tom--** [comment]
try again now
