### ISSUE TITLE
Repetition cache should be different among communication channels

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/ircbot#3]
When using the bot I often try my answer in a private conversation with the bot before posting to the channel, to see how it responds. This is to avoid confusing answers in situations where I am not exactly sure how a function is named.

The bot however caches which links he sent in the last n minutes and does not resend those links. This cache currently does not differentiate whether it has sent the link in the private conversation or in the channel. So when I post the correct function name in the channel, the bot does not respond.

**Comment by tom--** [comment]
e627f356c2a3ce125c66bdda47954cbac83d0933

thanks for the report

**Comment by cebe** [comment]
Awesome, it works. thanks for the quick fix :)
